name: lint test

on: push

jobs:

  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm ci
      - run: npm run lint
      - run: npm test
      - run: npm run build
